/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author elcontreras
 */
public class Escritorio extends javax.swing.JFrame {

    /**
     * Creates new form HumanWareEscritorio
     */
    public Escritorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo_HumanWare = new javax.swing.JLabel();
        Resumen_de_Fondo2 = new javax.swing.JLabel();
        Resumen_de_Fondo3 = new javax.swing.JLabel();
        Resumen_de_Fondo4 = new javax.swing.JLabel();
        Resumen_de_Fondo5 = new javax.swing.JLabel();
        Resumen_de_Fondo = new javax.swing.JLabel();
        Resumen_de_Fondo1 = new javax.swing.JLabel();
        Inicio = new javax.swing.JLabel();
        Busqueda_de_Empleo = new javax.swing.JLabel();
        Busqueda_de_Personal = new javax.swing.JLabel();
        NUESTRA_VISION = new javax.swing.JLabel();
        Contactos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Parte_Superior = new javax.swing.JLabel();
        ParteAzul = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo_HumanWare.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Logo_HumanWare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        Logo_HumanWare.setToolTipText("");
        getContentPane().add(Logo_HumanWare, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 40));

        Resumen_de_Fondo2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Resumen_de_Fondo2.setForeground(new java.awt.Color(255, 255, 255));
        Resumen_de_Fondo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Resumen_de_Fondo2.setText("su futura contratación");
        Resumen_de_Fondo2.setToolTipText("Especialistas en la búsqueda de empleo y análisis de personal para su futura contratación");
        Resumen_de_Fondo2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(Resumen_de_Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 380, -1));

        Resumen_de_Fondo3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Resumen_de_Fondo3.setForeground(new java.awt.Color(255, 255, 255));
        Resumen_de_Fondo3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Resumen_de_Fondo3.setText("de empleo y");
        Resumen_de_Fondo3.setToolTipText("Especialistas en la búsqueda de empleo y análisis de personal para su futura contratación");
        Resumen_de_Fondo3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(Resumen_de_Fondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 370, -1));

        Resumen_de_Fondo4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Resumen_de_Fondo4.setForeground(new java.awt.Color(255, 255, 255));
        Resumen_de_Fondo4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Resumen_de_Fondo4.setText("Especialistas en la búsqueda ");
        Resumen_de_Fondo4.setToolTipText("Especialistas en la búsqueda de empleo y análisis de personal para su futura contratación");
        Resumen_de_Fondo4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(Resumen_de_Fondo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 370, -1));

        Resumen_de_Fondo5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Resumen_de_Fondo5.setForeground(new java.awt.Color(255, 255, 255));
        Resumen_de_Fondo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Resumen_de_Fondo5.setText("análisis de personal para ");
        Resumen_de_Fondo5.setToolTipText("Especialistas en la búsqueda de empleo y análisis de personal para su futura contratación");
        Resumen_de_Fondo5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(Resumen_de_Fondo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 380, -1));

        Resumen_de_Fondo.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Resumen_de_Fondo.setForeground(new java.awt.Color(255, 255, 255));
        Resumen_de_Fondo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Resumen_de_Fondo.setText("y Personal");
        Resumen_de_Fondo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(Resumen_de_Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 30));

        Resumen_de_Fondo1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        Resumen_de_Fondo1.setForeground(new java.awt.Color(255, 255, 255));
        Resumen_de_Fondo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Resumen_de_Fondo1.setText("Búsqueda de Trabajo ");
        Resumen_de_Fondo1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(Resumen_de_Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        Inicio.setForeground(new java.awt.Color(0, 0, 153));
        Inicio.setText("INICIO");
        getContentPane().add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        Busqueda_de_Empleo.setForeground(new java.awt.Color(0, 0, 153));
        Busqueda_de_Empleo.setText("BUSQUEDA DE EMPLEO");
        Busqueda_de_Empleo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Busqueda_de_EmpleoMouseClicked(evt);
            }
        });
        getContentPane().add(Busqueda_de_Empleo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        Busqueda_de_Personal.setForeground(new java.awt.Color(0, 0, 153));
        Busqueda_de_Personal.setText("BUSQUEDA DE PERSONAL");
        getContentPane().add(Busqueda_de_Personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        NUESTRA_VISION.setForeground(new java.awt.Color(0, 0, 153));
        NUESTRA_VISION.setText("NUESTRA VISION");
        getContentPane().add(NUESTRA_VISION, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        Contactos.setForeground(new java.awt.Color(0, 0, 153));
        Contactos.setText("CONTACTANOS");
        getContentPane().add(Contactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("HUMAN WARE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, 20));

        Parte_Superior.setBackground(new java.awt.Color(255, 0, 0));
        Parte_Superior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Blanco.jpg"))); // NOI18N
        getContentPane().add(Parte_Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 70));
        getContentPane().add(ParteAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 410, 460));

        Fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edificios.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 900, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Busqueda_de_EmpleoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Busqueda_de_EmpleoMouseClicked
        // TODO add your handling code here:
        registro a = new registro();
        a.setVisible(true);
        
    }//GEN-LAST:event_Busqueda_de_EmpleoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Escritorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Escritorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Busqueda_de_Empleo;
    private javax.swing.JLabel Busqueda_de_Personal;
    private javax.swing.JLabel Contactos;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Inicio;
    private javax.swing.JLabel Logo_HumanWare;
    private javax.swing.JLabel NUESTRA_VISION;
    private javax.swing.JLabel ParteAzul;
    private javax.swing.JLabel Parte_Superior;
    private javax.swing.JLabel Resumen_de_Fondo;
    private javax.swing.JLabel Resumen_de_Fondo1;
    private javax.swing.JLabel Resumen_de_Fondo2;
    private javax.swing.JLabel Resumen_de_Fondo3;
    private javax.swing.JLabel Resumen_de_Fondo4;
    private javax.swing.JLabel Resumen_de_Fondo5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
